const ADD_TODO = 'ADD_TODO';
const EDIT_TODO = 'EDIT_TODO';
const DELETE_TODO = 'DELETE_TODO';
const FETCH_RSS = 'FETCH_RSS';
const FETCH_RSS_SUCCESS = 'FETCH_RSS_SUCCESS';
const FETCH_RSS_FAIL = 'FETCH_RSS_FAIL';

export {
    ADD_TODO,
    EDIT_TODO,
    DELETE_TODO,
    FETCH_RSS,
    FETCH_RSS_SUCCESS,
    FETCH_RSS_FAIL
}